name: coreutils
description: GNU Coreutils in Dart
dependencies:
  args: ">=0.13.0 <0.14.0"
  crypto: ">=0.9.0 <0.12.0"
  binary_interop: ">=0.0.19 <0.1.0"
  string_scanner: ">=0.0.13 <0.5.0"
  syscall:
    git: https://github.com/DirectMyFile/syscall.git